import 'package:flutter/material.dart';
import 'package:flutterapp/garapkabehapp/generatedmenuwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/garapkabehapp/generatedmenuwidget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/garapkabehapp/generatedmenuwidget/generated/GeneratedIPhoneXXS11Pro2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.46064794921875;

                  final double height =
                      constraints.maxHeight * 1.0751231527093597;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.3299812825520833,
                        y: constraints.maxHeight * -0.038177339901477834,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIPhoneXXS11Pro2Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10304733276367188;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 38.64274978637695;

                  double percentHeight = 0.054187192118226604;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 44.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.815935546875,
                        translateY: constraints.maxHeight * 0.7762237699161022,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              ),
              Positioned(
                left: 298.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedImage1Widget(),
              )
            ]),
      ),
    ));
  }
}
